[workspace]
members = [
  "dna/zomes/attestations",
  "dna/zomes/attestations_core",
  "dna/zomes/profiles",
  "dna/zomes/profiles_core"
  ]

[profile.dev]
opt-level = "z"

[profile.release]
opt-level = "z"
